# Generated by Django 4.0.10 on 2024-04-09 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('streaming_platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('intro', models.CharField(blank=True, max_length=100)),
                ('storyline', models.TextField(blank=True, max_length=1500)),
                ('year', models.IntegerField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('content_type', models.CharField(choices=[('Movies', 'Movies'), ('TV_series', 'TV Series'), ('Film_Series', 'Film Series'), ('Episodes', 'Episodes'), ('Documentaries', 'Documentaries')], max_length=20)),
                ('bbfc_rating', models.CharField(choices=[('U', 'Universal - Suitable for all ages.'), ('PG', 'Parental Guidance - Some scenes may be unsuitable for young children.'), ('12', '12A/12 - Suitable for 12 years and over.'), ('15', '15 - Suitable only for 15 years and over.'), ('18', '18 - Suitable only for adults.'), ('R18', 'Restricted 18 - Only available in licensed premises or sex shops.'), ('E', 'Exempt - Not subject to classification.'), ('TBC', 'To Be Confirmed - Rating is yet to be determined.')], default='U', help_text='Select the BBFC rating for this movie.', max_length=4, verbose_name='BBFC Rating')),
                ('avg_rating', models.FloatField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('popularity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('actors', models.ManyToManyField(related_name='acted_movies', to='casts.cast')),
                ('directors', models.ManyToManyField(related_name='directed_movies', to='casts.cast')),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='streaming_platforms.platform')),
                ('starring', models.ManyToManyField(related_name='starred_movies', to='casts.cast')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('intro', models.CharField(blank=True, max_length=100)),
                ('storyline', models.TextField(blank=True, max_length=1000)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('avg_rating', models.FloatField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('popularity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('intro', models.CharField(blank=True, max_length=100)),
                ('storyline', models.TextField(blank=True, max_length=1000)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('avg_rating', models.FloatField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('popularity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.season')),
            ],
        ),
        migrations.CreateModel(
            name='ContentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('viewed_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
