# Generated by Django 4.0.10 on 2024-04-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_genre_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='content_type',
            new_name='movie_type',
        ),
    ]
