# Generated by Django 4.0.10 on 2024-04-09 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('casts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='movies',
            field=models.ManyToManyField(related_name='casts', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='awardreceived',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casts.award'),
        ),
        migrations.AddField(
            model_name='awardreceived',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casts.cast'),
        ),
        migrations.AlterUniqueTogether(
            name='awardreceived',
            unique_together={('recipient', 'award')},
        ),
    ]
