# Generated by Django 4.0.10 on 2024-04-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardreceived',
            options={'verbose_name_plural': 'Awards Received'},
        ),
    ]
