# Generated by Django 4.0.10 on 2024-04-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0003_alter_awardreceived_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='created_at',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='cast',
            old_name='updated_at',
            new_name='date_modified',
        ),
    ]
