# Generated by Django 4.0.10 on 2024-04-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=1000)),
                ('website', models.URLField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modeified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
