# Generated by Django 4.0.10 on 2024-04-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platforms', '0002_rename_date_modeified_platform_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='website',
            field=models.URLField(unique=True),
        ),
    ]
