# Generated by Django 4.0.10 on 2024-04-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platforms', '0003_alter_platform_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
