# Generated by Django 4.0.10 on 2024-04-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_names_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_an_actor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
