# Generated by Django 4.0.10 on 2024-04-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_an_actor_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_a_director',
            field=models.BooleanField(default=False),
        ),
    ]
