# Generated by Django 4.0.10 on 2024-04-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_is_a_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_a_director',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_an_actor',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
